# Generated by Django 3.2.9 on 2022-04-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomCabinet', models.CharField(max_length=60, unique=True)),
                ('lateture', models.IntegerField(blank=True, null=True)),
                ('languetude', models.IntegerField(blank=True, null=True)),
                ('addresse', models.CharField(blank=True, max_length=60, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='cabinet')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='cabinet')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='cabinet')),
                ('telephone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('img_medecin', models.ImageField(blank=True, null=True, upload_to='medecin')),
                ('nom_medecin', models.CharField(blank=True, max_length=20, null=True)),
                ('prenom_medecin', models.CharField(blank=True, max_length=20, null=True)),
                ('genre', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10, null=True)),
                ('date_naiss', models.DateField(null=True)),
                ('biographie', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=60)),
                ('duree', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
                ('Cabinet', models.CharField(blank=True, max_length=60, null=True)),
                ('jours', models.ManyToManyField(related_name='motif', to='Patient.jour')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCartCredit', models.PositiveIntegerField()),
                ('DateExpiration', models.DateField()),
                ('code', models.PositiveIntegerField()),
                ('credit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPatient', models.CharField(blank=True, max_length=20, null=True)),
                ('prenomPatient', models.CharField(blank=True, max_length=20, null=True)),
                ('emailPatient', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('date_naiss', models.DateField(null=True)),
                ('genre', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10, null=True)),
                ('img_patient', models.ImageField(blank=True, null=True, upload_to='patient')),
            ],
        ),
        migrations.CreateModel(
            name='specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRV', models.DateField()),
                ('heureRV', models.TimeField()),
                ('status', models.CharField(choices=[('confirmé', 'confirmé'), ('non_confirmé', 'non_confirmé')], max_length=15)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.cabinet')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.motif')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.paiement')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=20)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.cabinet')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.commune'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.specialite'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.wilaya'),
        ),
    ]
