# Generated by Django 3.2.9 on 2022-04-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_patient_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.commune'),
        ),
        migrations.AddField(
            model_name='patient',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.wilaya'),
        ),
    ]
