# Generated by Django 3.2.9 on 2022-04-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_auto_20220419_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='genre',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rv',
            name='status',
            field=models.CharField(choices=[('non_confirmé', 'non_confirmé'), ('confirmé', 'confirmé')], max_length=15),
        ),
    ]
