# Generated by Django 3.2.9 on 2022-04-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20220419_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rv',
            name='status',
            field=models.CharField(choices=[('confirmé', 'confirmé'), ('non_confirmé', 'non_confirmé')], max_length=15),
        ),
    ]
