# Generated by Django 3.2.9 on 2022-04-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_alter_rv_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='commune',
        ),
    ]
