# Generated by Django 3.2.9 on 2022-04-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_auto_20220424_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinet',
            old_name='languetude',
            new_name='GeoAdress',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='lateture',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='specialite',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='specialite',
            field=models.ManyToManyField(blank=True, related_name='specialites', to='Patient.specialite'),
        ),
        migrations.AlterField(
            model_name='rv',
            name='status',
            field=models.CharField(choices=[('non_confirmé', 'non_confirmé'), ('confirmé', 'confirmé')], max_length=15),
        ),
    ]
