# Generated by Django 3.2.9 on 2022-04-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_auto_20220425_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='img1',
            field=models.ImageField(blank=True, default='anonymous_user.jpg', null=True, upload_to='cabinet'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='img2',
            field=models.ImageField(blank=True, default='anonymous_user.jpg', null=True, upload_to='cabinet'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='img3',
            field=models.ImageField(blank=True, default='anonymous_user.jpg', null=True, upload_to='cabinet'),
        ),
        migrations.AlterField(
            model_name='rv',
            name='status',
            field=models.CharField(choices=[('confirmé', 'confirmé'), ('non_confirmé', 'non_confirmé')], max_length=15),
        ),
    ]
