# Generated by Django 3.2.9 on 2022-04-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0012_auto_20220427_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='commune',
        ),
    ]
