# Generated by Django 3.2.9 on 2022-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_auto_20220502_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motif',
            old_name='jours',
            new_name='jour',
        ),
        migrations.AlterField(
            model_name='motif',
            name='duree',
            field=models.PositiveIntegerField(choices=[('6', 45), ('3', 15), ('4', 20), ('7', 60), ('5', 30), ('1', 5), ('2', 10)]),
        ),
    ]
