# Generated by Django 3.2.9 on 2022-05-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0015_auto_20220502_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motif',
            old_name='jour',
            new_name='j',
        ),
        migrations.AlterField(
            model_name='motif',
            name='duree',
            field=models.PositiveIntegerField(choices=[('5', 30), ('7', 60), ('3', 15), ('2', 10), ('1', 5), ('4', 20), ('6', 45)]),
        ),
    ]
