# Generated by Django 3.2.9 on 2022-05-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0017_auto_20220503_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rv',
            name='heureRV',
        ),
        migrations.AlterField(
            model_name='motif',
            name='duree',
            field=models.PositiveIntegerField(choices=[(1, 5), (2, 10), (3, 15), (4, 20), (5, 30), (6, 45), (7, 60)]),
        ),
        migrations.AlterField(
            model_name='rv',
            name='paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.paiement'),
        ),
        migrations.AlterField(
            model_name='rv',
            name='status',
            field=models.CharField(choices=[('annulé', 'annulé'), ('non_confirmé', 'non_confirmé'), ('en_attante', 'en_attante'), ('completé', 'completé')], max_length=15),
        ),
    ]
