# Generated by Django 3.2.9 on 2022-05-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0018_auto_20220506_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_medecin', models.ImageField(blank=True, null=True, upload_to='medecin')),
                ('nom_medecin', models.CharField(blank=True, max_length=20, null=True)),
                ('prenom_medecin', models.CharField(blank=True, max_length=20, null=True)),
                ('genre', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=10, null=True)),
                ('date_naiss', models.DateField(blank=True, null=True)),
                ('biographie', models.TextField(blank=True, null=True)),
                ('rempalçant', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('NomCabinet', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('telephone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('addresse', models.CharField(blank=True, max_length=60, null=True)),
                ('GeoAdress', models.IntegerField(blank=True, null=True)),
                ('img1', models.ImageField(blank=True, default='anonymous_user.jpg', null=True, upload_to='cabinet')),
                ('img2', models.ImageField(blank=True, default='anonymous_user.jpg', null=True, upload_to='cabinet')),
                ('img3', models.ImageField(blank=True, default='anonymous_user.jpg', null=True, upload_to='cabinet')),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.commune')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.specialite')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='RV_valide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRV', models.DateField()),
                ('status', models.CharField(choices=[('completé', 'completé'), ('annulé', 'annulé'), ('en_attante', 'en_attante')], max_length=15)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='type_consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.PositiveIntegerField(choices=[(1, 15), (2, 30), (3, 45), (4, 60), (5, 90)])),
                ('prix', models.PositiveIntegerField()),
                ('j', models.CharField(blank=True, choices=[('dimenche', 'Dimenche'), ('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=10, null=True)),
                ('start', models.TimeField(default='0:0')),
                ('end', models.TimeField(default='0:0')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.medecin')),
            ],
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='wilaya',
        ),
        migrations.RemoveField(
            model_name='motif',
            name='Cabinet',
        ),
        migrations.RemoveField(
            model_name='motif',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='motif',
            name='end',
        ),
        migrations.RemoveField(
            model_name='motif',
            name='j',
        ),
        migrations.RemoveField(
            model_name='motif',
            name='motif',
        ),
        migrations.RemoveField(
            model_name='motif',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='motif',
            name='start',
        ),
        migrations.RemoveField(
            model_name='rv',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='rv',
            name='dateRV',
        ),
        migrations.RemoveField(
            model_name='rv',
            name='motif',
        ),
        migrations.RemoveField(
            model_name='rv',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='rv',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='rv',
            name='status',
        ),
        migrations.AddField(
            model_name='motif',
            name='nomMotif',
            field=models.CharField(blank=True, choices=[('1', 'consultation génerale'), ('2', 'motif2'), ('3', 'motif3')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='rv',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='jour',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
        migrations.AddField(
            model_name='type_consultation',
            name='motif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.motif'),
        ),
        migrations.AddField(
            model_name='rv_valide',
            name='type_consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.type_consultation'),
        ),
        migrations.AddField(
            model_name='rv',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.medecin'),
        ),
        migrations.AddField(
            model_name='rv',
            name='type_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.type_consultation'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.medecin'),
        ),
        migrations.DeleteModel(
            name='Cabinet',
        ),
    ]
