# Generated by Django 3.2.9 on 2022-05-12 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0019_auto_20220511_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='rempalçant',
        ),
        migrations.RemoveField(
            model_name='rv',
            name='type_consultation',
        ),
        migrations.AddField(
            model_name='rv',
            name='duree',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rv',
            name='heure',
            field=models.TimeField(default='0:0'),
        ),
        migrations.AddField(
            model_name='rv',
            name='motif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.motif'),
        ),
        migrations.AlterField(
            model_name='motif',
            name='nomMotif',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='type_consultation',
            name='j',
            field=models.CharField(blank=True, choices=[('Dimenche', 'Dimenche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10, null=True),
        ),
    ]
