# Generated by Django 3.2.9 on 2022-05-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0020_auto_20220512_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RV',
        ),
    ]
