# Generated by Django 3.2.9 on 2022-05-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0021_delete_rv'),
    ]

    operations = [
        migrations.CreateModel(
            name='RV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('heure', models.TimeField(default='0:0')),
                ('duree', models.PositiveIntegerField(blank=True, null=True)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.medecin')),
                ('motif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.motif')),
            ],
        ),
    ]
