# Generated by Django 3.2.9 on 2022-05-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0022_rv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_consultation',
            name='duree',
            field=models.IntegerField(choices=[(1, 15), (2, 30), (3, 45), (4, 60), (5, 90)]),
        ),
    ]
