# Generated by Django 3.2.9 on 2022-05-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0023_alter_type_consultation_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rv',
            name='motif',
        ),
        migrations.AddField(
            model_name='rv',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.type_consultation'),
        ),
        migrations.AlterField(
            model_name='type_consultation',
            name='duree',
            field=models.IntegerField(choices=[(15, 15), (30, 30), (45, 45), (60, 60), (90, 90)]),
        ),
    ]
