# Generated by Django 3.2.9 on 2022-05-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0024_auto_20220514_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='rv_valide',
            name='heure',
            field=models.TimeField(default='0:0'),
        ),
    ]
