# Generated by Django 3.2.9 on 2022-05-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0026_auto_20220520_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.commune'),
        ),
        migrations.AlterField(
            model_name='rv_valide',
            name='status',
            field=models.CharField(choices=[('completé', 'completé'), ('annulé', 'annulé'), ('confirmé', 'confirmé')], max_length=15),
        ),
    ]
