# Generated by Django 3.2.9 on 2022-05-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0027_auto_20220521_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='GeoAdress',
        ),
    ]
