# Generated by Django 3.2.9 on 2022-05-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0028_remove_medecin_geoadress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(blank=True, max_length=254, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('new', models.BooleanField(default=True)),
            ],
        ),
    ]
