# Generated by Django 3.2.9 on 2022-05-24 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0029_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('date_naiss', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rv_valide',
            name='pour_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rv_valide',
            name='anonymous_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.anonymous'),
        ),
    ]
