# Generated by Django 3.2.9 on 2022-05-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0030_auto_20220524_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
