# Generated by Django 3.2.9 on 2022-05-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0031_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='googlemaps_iframe',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='img1',
            field=models.ImageField(blank=True, default='anonymous_clinic.jpg', null=True, upload_to='cabinet'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='img2',
            field=models.ImageField(blank=True, default='anonymous_clinic.jpg', null=True, upload_to='cabinet'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='img3',
            field=models.ImageField(blank=True, default='anonymous_clinic.jpg', null=True, upload_to='cabinet'),
        ),
        migrations.CreateModel(
            name='MedecinFavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
    ]
