# Generated by Django 3.2.9 on 2022-05-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0032_auto_20220528_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentaire',
            new_name='Avi',
        ),
    ]
