# Generated by Django 3.2.9 on 2022-05-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0033_rename_commentaire_avi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avi',
            name='rating',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='rating',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
