# Generated by Django 3.2.9 on 2022-06-01 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0036_auto_20220529_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='Date_signIn',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 1), null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Date_signIn',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 1), null=True),
        ),
    ]
